/**
 * Copyright IBM Corp. 2021, 2026
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktn get
Object.defineProperty(exports, 'customResource', { get: function () { return require('./custom-resource'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });
Object.defineProperty(exports, 'providerFunctions', { get: function () { return require('./provider-functions'); } });

